services:
  - type: web
    name: Fidaro-Vastgoed
    env: static
    buildCommand: "npm install --legacy-peer-deps && npm run build"
    publishDir: "frontend/build"
    routes:
      - src: "/*"
        dest: "/index.html"